name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            doctest-dev \
            libmagicenum-dev \
            libsdl3-dev \
            libstb-dev \
            libtomlplusplus-dev \
            libvulkan-dev \
            libwayland-dev \
            libx11-dev \
            mesa-vulkan-drivers \
            pkg-config \
            wayland-protocols \
            xvfb

      - name: Build
        run: make -j$(nproc)
